### PR TITLE
add roгter, fix warnings, deleted console output from App.js

### LINKED ISSUE #18: fix warnings from console output

### PR DESCRIPTION
**Pull request by vadim9999**
Fixes #18, #26

### CODE REVIEW

File: src/Router.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+import { BrowserRouter, Switch, Route } from 'react-router-dom';
+import App from './App';
+import Meal from './components/Meal/Meal';
+class Router extends Component {
+  render(){
+    return (
+      <BrowserRouter>
+        <Switch>
+          <Route path="/" exact component={App}/>
+          <Route path="/meal/:id" component={Meal}/>
```
Comment (atherdon) [inline src/Router.js]: i'm not sure that in showcase we're showing meal. looks like copy-paste :)

File: src/components/Meal/Meal.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import React, { Component } from 'react';
+
+import data from '@groceristar/groceristar-fetch/chickenKyiv';
+import DisplayList from '../DisplayList/DisplayList'
+
+class Meal extends Component {
```
Comment (atherdon) [inline src/components/Meal/Meal.js]: Got it. Sorry, i think i was not clear. My idea was to have a router, that will display data, related to grocery lists.
like if you open /xxx/:id - you'll see a single grocery list with all necessary data, as we have at tiles.

But, as we added meal components and route - let's keep it - we'll use it somehow later.

**Comment by atherdon** [comment]
if we fixes warning - please close that task

File: src/components/Cell/Cell.js [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+import {Slug, Fade} from 'mauerwerk'
+
+
+import { RenderGrocery } from '../RenderGrocery/RenderGrocery'
+
+
+
+const Cell = ({ toggle, name, height, description, css, maximized }) => (
+			<div
```
Comment (atherdon) [inline src/components/Cell/Cell.js]: please format the HTML part
